# Generated by Django 3.1.1 on 2020-09-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200922_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-pro-pic.jpg', null=True, upload_to=''),
        ),
    ]
